DROP SCHEMA IF EXISTS trabalho1_crud;
CREATE SCHEMA IF NOT EXISTS trabalho1_crud;

USE trabalho1_crud;

DROP TABLE IF EXISTS trabalho1_crud.products;
CREATE TABLE IF NOT EXISTS trabalho1_crud.products(
	id int auto_increment PRIMARY KEY,
    name_product VARCHAR(255) NOT NULL,
    description_product VARCHAR(255) NOT NULL,
    price float NOT NULL,
    stock int NOT NULL,
    available_online boolean NOT NULL
);

INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Sleek Fresh Mouse', 'Bostons most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles', '149.00', '1', '0');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Incredible Rubber Shoes', 'Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support', '61.00', '3', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Handmade Fresh Mouse', 'The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design', '143.00', '101', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Refined Wooden Gloves', 'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients', '145.00', '103', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Electronic Cotton Ball', 'The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design', '156.00', '90', '0');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Awesome Concrete Gloves', 'The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality', '123.00', '32', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Sleek Wooden Towels', 'The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive', '186.00', '60', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Refined Cotton Pizza', 'Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals', '81.00', '131', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Electronic Metal Tuna', 'The Football Is Good For Training And Recreational Purposes', '79.00', '122', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Elegant Concrete Mouse', 'The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design', '49.00', '57', '0');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Tasty Metal Cheese', 'New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016', '39.00', '39', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Tasty Bronze Table', 'The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive', '13.00', '77', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Intelligent Soft Table', 'The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design', '76.00', '85', '0');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Awesome Rubber Shoes', 'The Football Is Good For Training And Recreational Purposes', '151.00', '155', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Modern Bronze Car', 'Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals', '83.00', '101', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Fantastic Plastic Bike', 'The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J', '117.00', '22', '0');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Electronic Concrete Hat', 'The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J', '154.00', '170', '0');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Generic Metal Bike', 'Carbonite web goalkeeper gloves are ergonomically designed to give easy fit', '148.00', '192', '0');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Unbranded Bronze Mouse', 'The Football Is Good For Training And Recreational Purposes', '135.00', '139', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Oriental Concrete Fish', 'New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016', '107.00', '143', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Handcrafted Bronze Chair', 'The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design', '47.00', '154', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Rustic Plastic Tuna', 'Carbonite web goalkeeper gloves are ergonomically designed to give easy fit', '77.00', '151', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Elegant Frozen Ball', 'Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals', '65.00', '182', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Licensed Metal Hat', 'New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016', '141.00', '90', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Small Bronze Cheese', 'Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals', '121.00', '183', '0');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Incredible Plastic Towels', 'The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality', '10.00', '58', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Elegant Granite Keyboard', 'The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality', '32.00', '48', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Intelligent Steel Towels', 'The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive', '186.00', '92', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Recycled Steel Gloves', 'The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design', '79.00', '131', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Intelligent Frozen Chicken', 'The Football Is Good For Training And Recreational Purposes', '108.00', '150', '0');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Rustic Plastic Cheese', 'Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support', '49.00', '87', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Recycled Concrete Table', 'The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J', '200.00', '78', '0');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Gorgeous Wooden Table', 'The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive', '126.00', '30', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Practical Plastic Salad', 'The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design', '28.00', '146', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Gorgeous Metal Pants', 'The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive', '19.00', '181', '0');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Oriental Concrete Towels', 'The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive', '123.00', '155', '0');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Licensed Metal Car', 'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients', '62.00', '141', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Sleek Plastic Ball', 'Bostons most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles', '85.00', '107', '0');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Elegant Plastic Bike', 'The Football Is Good For Training And Recreational Purposes', '149.00', '95', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Incredible Concrete Sausages', 'The Football Is Good For Training And Recreational Purposes', '163.00', '86', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Sleek Fresh Fish', 'Carbonite web goalkeeper gloves are ergonomically designed to give easy fit', '153.00', '71', '0');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Licensed Concrete Chair', 'The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive', '40.00', '80', '0');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Electronic Rubber Keyboard', 'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart', '144.00', '185', '0');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Ergonomic Plastic Towels', 'Carbonite web goalkeeper gloves are ergonomically designed to give easy fit', '57.00', '149', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Fantastic Steel Shirt', 'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients', '86.00', '86', '0');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Gorgeous Fresh Chair', 'The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality', '66.00', '10', '0');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Refined Frozen Towels', 'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart', '31.00', '72', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Small Steel Soap', 'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart', '68.00', '84', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Bespoke Cotton Cheese', 'Carbonite web goalkeeper gloves are ergonomically designed to give easy fit', '167.00', '19', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Gorgeous Metal Chips', 'The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design', '81.00', '118', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Rustic Metal Chips', 'The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J', '95.00', '14', '0');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Tasty Rubber Salad', 'The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality', '131.00', '4', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Modern Soft Pizza', 'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients', '34.00', '167', '0');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Elegant Plastic Chicken', 'New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016', '36.00', '114', '0');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Unbranded Cotton Chicken', 'Bostons most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles', '55.00', '191', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Small Rubber Sausages', 'Bostons most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles', '165.00', '118', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Small Plastic Table', 'The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality', '188.00', '8', '0');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Bespoke Concrete Chicken', 'The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J', '171.00', '67', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Fantastic Wooden Fish', 'Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals', '161.00', '99', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Unbranded Soft Table', 'The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design', '131.00', '149', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Recycled Frozen Chicken', 'The Football Is Good For Training And Recreational Purposes', '155.00', '102', '0');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Tasty Bronze Bacon', 'The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J', '158.00', '74', '0');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Handcrafted Cotton Mouse', 'The Football Is Good For Training And Recreational Purposes', '16.00', '121', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Fantastic Bronze Pants', 'Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support', '90.00', '25', '0');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Intelligent Granite Computer', 'The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J', '195.00', '116', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Luxurious Granite Fish', 'Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals', '55.00', '143', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Elegant Soft Soap', 'Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support', '41.00', '199', '0');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Sleek Frozen Tuna', 'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart', '59.00', '188', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Handcrafted Cotton Computer', 'The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J', '172.00', '186', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Intelligent Metal Sausages', 'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients', '151.00', '138', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Incredible Bronze Fish', 'The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J', '77.00', '34', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Modern Metal Chips', 'The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design', '57.00', '63', '0');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Bespoke Rubber Ball', 'Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support', '137.00', '149', '0');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Ergonomic Cotton Cheese', 'Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support', '36.00', '197', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Rustic Cotton Table', 'The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive', '186.00', '167', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Handmade Fresh Tuna', 'Bostons most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles', '36.00', '40', '0');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Sleek Soft Gloves', 'The Football Is Good For Training And Recreational Purposes', '71.00', '170', '0');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Ergonomic Soft Bike', 'Carbonite web goalkeeper gloves are ergonomically designed to give easy fit', '179.00', '27', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Intelligent Steel Sausages', 'Carbonite web goalkeeper gloves are ergonomically designed to give easy fit', '198.00', '2', '0');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Handmade Concrete Hat', 'Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support', '35.00', '111', '0');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Sleek Metal Bacon', 'Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals', '47.00', '1', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Unbranded Concrete Chicken', 'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart', '189.00', '6', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Generic Cotton Hat', 'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart', '80.00', '142', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Ergonomic Cotton Tuna', 'Bostons most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles', '148.00', '78', '0');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Generic Wooden Pants', 'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients', '133.00', '86', '0');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Bespoke Soft Tuna', 'The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality', '14.00', '161', '0');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Tasty Concrete Tuna', 'The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J', '162.00', '8', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Tasty Concrete Cheese', 'Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals', '51.00', '13', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Fantastic Granite Bacon', 'The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive', '132.00', '49', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Generic Steel Bike', 'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart', '199.00', '59', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Handmade Concrete Car', 'The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality', '150.00', '129', '0');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Electronic Soft Ball', 'The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J', '196.00', '169', '0');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Intelligent Cotton Car', 'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients', '141.00', '91', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Intelligent Soft Sausages', 'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients', '154.00', '172', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Ergonomic Soft Gloves', 'The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality', '11.00', '22', '0');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Modern Fresh Ball', 'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients', '54.00', '109', '0');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Intelligent Rubber Keyboard', 'Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support', '129.00', '80', '0');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Gorgeous Metal Table', 'The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design', '40.00', '94', '1');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Refined Steel Computer', 'The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality', '164.00', '38', '0');
INSERT INTO products (name_product, description_product, price, stock, available_online) VALUES ('Sleek Metal Chair', 'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart', '91.00', '47', '0');

SELECT * FROM products WHERE id < 10;